### ISSUE TITLE
submodule link out of compliance

### ISSUE THREAD

**Issue by tofr** [alasday/Yabe#1]
PM, I would call your attention to the last bullet point on the deliverable breakdown:

Submodule linking notes:
Make sure your submodule link appears as follows:
NameOfTeam_ALastF-BLastF-CLastF-DLastF
(e.g., Savages_BethJ-HassanA-MiltonF-ThompsonG)
Note that your repo itself can be named anything you like -- perhaps something indicative of purpose?

**Comment by alasday** [comment]
Hi Mr. Brown,

Sorry, I was about to change it but the bell rang and my next teacher is
really intense about lateness my apologies. I will make the change when I
get home.

Best,

Asher
